# Site settings
title: In Case of Kernel Panic...
email: deepfreeze32@gmail.com
description: > 
  What should you do when you have a Kernel Panic? Reboot!
  Or settle for reading this awesome blog on a device that
  you aren't screwing up the hardware for. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://incaseofkernelpanic.com" # the base hostname & protocol for your site
github_username:  Deepfreeze32
about: About me
copyright: © 2015 Travis Cramer

# Build settings
markdown: kramdown
